"""Exercise the release baseline in a disposable local MariaDB database."""

from __future__ import annotations

import argparse
import getpass
import secrets
from datetime import datetime
from pathlib import Path

import mariadb

from baseline_installer import BaselineInstaller, load_baseline, load_seed
from database_provisioning import FreshDatabaseProvisioner, quote_identifier
from migration_service import MigrationService
from authentication import MariaDBUserRepository, PasswordService
from initial_master import InitialMasterBootstrapper


ROOT = Path(__file__).resolve().parent
MIGRATIONS = ROOT / "migrations"
SCHEMA = ROOT / "installation" / "baseline_schema.sql"
MANIFEST = ROOT / "installation" / "baseline_manifest.json"
SEED = ROOT / "installation" / "baseline_seed.sql"
SEED_MANIFEST = ROOT / "installation" / "baseline_seed_manifest.json"
SAFE_PREFIX = "CMFreshAcceptance_"
SAFE_ACCOUNT_PREFIX = "cm_accept_"


class FreshInstallAcceptanceError(RuntimeError):
    """Raised when isolated fresh-install acceptance cannot be completed."""


def disposable_names(now=None):
    """Return unique, visibly temporary database and account identifiers."""
    stamp = (now or datetime.now()).strftime("%Y%m%d%H%M%S")
    return SAFE_PREFIX + stamp, SAFE_ACCOUNT_PREFIX + stamp


def _drop_disposable(admin_connection, database_name, account_name):
    """Remove only identifiers generated by this acceptance command."""
    if not database_name.startswith(SAFE_PREFIX):
        raise FreshInstallAcceptanceError("Refusing to remove an unrecognized database.")
    if not account_name.startswith(SAFE_ACCOUNT_PREFIX):
        raise FreshInstallAcceptanceError("Refusing to remove an unrecognized account.")
    cursor = admin_connection.cursor()
    try:
        cursor.execute(f"DROP USER IF EXISTS '{account_name}'@'127.0.0.1'")
        cursor.execute(f"DROP DATABASE IF EXISTS {quote_identifier(database_name)}")
    finally:
        cursor.close()


def accept(admin_password, *, host="127.0.0.1", port=3306, keep=False, notify=print):
    """Create, install, verify, and normally remove one isolated database."""
    schema, manifest = load_baseline(SCHEMA, MANIFEST, MIGRATIONS)
    seed_sql, seed_manifest = load_seed(SEED, SEED_MANIFEST, MIGRATIONS)
    database_name, account_name = disposable_names()
    application_password = secrets.token_urlsafe(32)
    admin = None
    application = None
    created = False
    succeeded = False
    try:
        admin = mariadb.connect(
            host=host, port=port, user="root", password=admin_password,
            autocommit=True,
        )
        FreshDatabaseProvisioner(admin, database_errors=(mariadb.Error,)).create(
            database_name, account_name, application_password,
            application_host="127.0.0.1", confirmation=database_name,
        )
        created = True
        notify(f"created isolated database {database_name}")
        application = mariadb.connect(
            host=host, port=port, user=account_name,
            password=application_password, database=database_name,
        )
        result = BaselineInstaller(
            application, database_errors=(mariadb.Error,),
        ).install(schema, manifest, seed_sql)
        migration_result = MigrationService(
            application, MIGRATIONS, database_errors=(mariadb.Error,),
        ).run()
        if migration_result.pending:
            raise FreshInstallAcceptanceError(
                "The installed baseline left numbered migrations pending."
            )
        master_password = secrets.token_urlsafe(24)
        master_id = InitialMasterBootstrapper(application).create(
            "acceptance_admin", "Acceptance Administrator",
            master_password, master_password,
        )
        account = MariaDBUserRepository(application).find_by_username("acceptance_admin")
        if not account or not account.is_master:
            raise FreshInstallAcceptanceError(
                "The initial Master Administrator did not verify."
            )
        if not PasswordService().verify(account.password_hash, master_password):
            raise FreshInstallAcceptanceError(
                "The initial Master Administrator password did not verify."
            )
        master_password = ""
        succeeded = True
        notify(f"verified {result['database_objects']} database objects")
        notify(f"verified {result['represented_migrations']} migration checksums")
        notify(f"verified {result['active_permissions']} active permissions")
        notify(f"verified starter-data SHA-256 {seed_manifest['seed_sha256']}")
        notify(f"verified initial Master Administrator ID {master_id}")
        notify(f"verified schema SHA-256 {result['schema_sha256']}")
        return result
    except mariadb.Error as error:
        raise FreshInstallAcceptanceError(
            "MariaDB could not complete the isolated fresh-install acceptance."
        ) from error
    finally:
        application_password = ""
        if application is not None:
            application.close()
        if admin is not None:
            if created and (not keep or not succeeded):
                _drop_disposable(admin, database_name, account_name)
                notify(f"removed isolated database {database_name}")
            admin.close()


def main(argv=None):
    """Run preview by default or interactive isolated acceptance with --apply."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument(
        "--keep", action="store_true",
        help="Keep a successful disposable database for explicit inspection.",
    )
    args = parser.parse_args(argv)
    schema, manifest = load_baseline(SCHEMA, MANIFEST, MIGRATIONS)
    seed_sql, seed_manifest = load_seed(SEED, SEED_MANIFEST, MIGRATIONS)
    database_name, account_name = disposable_names()
    print(f"release={manifest['release_version']}")
    print(f"schema_bytes={len(schema.encode('utf-8'))}")
    print(f"represented_migrations={len(manifest['represented_migrations'])}")
    print(f"seed_bytes={len(seed_sql.encode('utf-8'))}")
    print(f"seed_statements={seed_manifest['statement_count']}")
    print(f"temporary_database_pattern={database_name}")
    print(f"temporary_account_pattern={account_name}")
    if not args.apply:
        print("preview_only=true")
        return 0
    password = getpass.getpass("Local MariaDB administrative password for root: ")
    try:
        accept(password, keep=args.keep)
    finally:
        password = ""
    print("fresh_install_baseline_accepted=true")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
