"""Stable permissions used by ChurchManager's current main menu."""


MAIN_MENU_PERMISSIONS = {
    "lblChurch": "church.manage",
    "lblService": "worship.manage",
    "lblSermon": "worship.manage",
    "lblPropers": "worship.manage",
    "lblOS": "worship.manage",
    "lblPrayers": "worship.manage",
    "lblParticipant": "worship.manage",
    "lblSchedule": "worship.manage",
    "lblServiceSchedule": "worship.manage",
    "lblOSList": "worship.manage",
    "lblAttendanceEvent": "attendance.events.manage",
    "lblPerson": "membership.manage",
    "lblFamily": "membership.manage",
    "lblRecordAttendance": "attendance.record",
    "lblProject": "ministry.manage",
    "lblTask": "ministry.manage",
    "lblDocument": "ministry.manage",
    "lblAnnouncement": "ministry.manage",
    "lblJournal": "ministry.manage",
    "lblReports": "reports.run",
    "lblGenerateOS": "worship.manage",
    "lblNotifyParticipants": "worship.manage",
    "lblSundayPrayers": "worship.manage",
    "lblAnnouncements": "worship.manage",
    "lblConfig": "application.config.manage",
    "lblOptions": "application.config.manage",
    "lblChoices": "application.config.manage",
    "lblCheckList": "application.config.manage",
    "lblUsers": "security.users.manage",
    "lblBackupDB": "application.backup.run",
    "lblEnhancements": "application.enhancements.manage",
    "lblAccountingSetup": "accounting.master_data.manage",
    "lblAccountingAccounts": "accounting.master_data.manage",
    "lblAccountingFunds": "accounting.master_data.manage",
    "lblAccountingFunctions": "accounting.master_data.manage",
    "lblAccountingYears": "accounting.master_data.manage",
    "lblAccountingPeriods": "accounting.master_data.manage",
    "lblAccountingTransactions": "accounting.transactions.create",
    "lblAccountingReview": "accounting.transactions.approve",
    "lblAccountingPosting": "accounting.transactions.post",
    "lblAccountingRegister": "accounting.transactions.view",
    "lblAccountingTrialBalance": "accounting.reports.run",
    "lblAccountingPosition": "accounting.reports.run",
    "lblAccountingActivities": "accounting.reports.run",
}
