-- Normalize legacy test links, then convert every remaining MyISAM table.
UPDATE tblChurch
SET Church = CASE ID WHEN 0 THEN 'Reformation Lutheran Church' ELSE CONCAT('Test Church ', ID) END;

UPDATE tblService SET ChurchID = 0;
UPDATE tblHymnUsage SET ChurchID = 0;
UPDATE tblAttendanceEvent SET ChurchID = 0;

UPDATE tblTask
SET ProjectID = CASE MOD(ID, 11)
    WHEN 0 THEN 15 WHEN 1 THEN 17 WHEN 2 THEN 21 WHEN 3 THEN 22
    WHEN 4 THEN 27 WHEN 5 THEN 30 WHEN 6 THEN 31 WHEN 7 THEN 33
    WHEN 8 THEN 35 WHEN 9 THEN 36 ELSE 37 END;

ALTER TABLE tblAltReading ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblAnnouncement ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblAsset ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblAttendance ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblAttendanceEvent ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblCheckList ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblChoices ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblChurch ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblChurchinfo ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblConfig ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblDocument ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblEnhancement ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblFamily ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblFamilyAddress ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblFamilyContact ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblFamilyDate ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblGroup ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblGroupMember ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblHymn ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblHymnal ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblHymnUsage ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblJournal ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblOptions ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblOrderofService ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblParticipant ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblPastor ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblPerson ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblPersonAddress ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblPersonContact ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblPersonDate ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblPrayer ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblProject ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblPropers ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblReading ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblReports ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblSchedule ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblSermon ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblService ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblServiceRole ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblStates ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblTask ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE tblTaskWorker ENGINE=InnoDB ROW_FORMAT=DYNAMIC;

