-- Tune-name metadata for the 636 hymns printed in Lutheran Service Book.
-- Service Builder-only records intentionally remain without a tune.

ALTER TABLE tblHymn
    ADD COLUMN IF NOT EXISTS Tune varchar(160) NULL AFTER Title;

CREATE TEMPORARY TABLE tmp_lsb_printed_tune (
    HymnNumber int PRIMARY KEY,
    Title varchar(255) NOT NULL,
    Tune varchar(160) NOT NULL
);

INSERT INTO tmp_lsb_printed_tune (HymnNumber,Title,Tune) VALUES
(331,'The Advent of Our King','ST. THOMAS'),
(332,'Savior of the Nations, Come','NUN KOMM, DER HEIDEN HEILAND'),
(333,'Once He Came in Blessing','GOTTES SOHN IST KOMMEN'),
(334,'O Lord, How Shall I Meet You','WIE SOLL ICH DICH EMPFANGEN'),
(335,'O Bride of Christ, Rejoice','WO SOLL ICH FLIEHEN HIN'),
(336,'Lo! He Comes with Clouds Descending','HELMSLEY'),
(337,'The Night Will Soon Be Ending','LLANGLOFFAN'),
(338,'Come, Thou Long-Expected Jesus','JEFFERSON'),
(339,'Lift Up Your Heads, You Everlasting Doors','CONRAD'),
(340,'Lift Up Your Heads, Ye Mighty Gates','MACHT HOCH DIE TÜR'),
(341,'Lift Up Your Heads, Ye Mighty Gates','MILWAUKEE'),
(342,'What Hope! An Eden Prophesied','CONSOLATION'),
(343,'Prepare the Royal Highway','BEREDEN VÄG FÖR HERRAN'),
(344,'On Jordan''s Bank the Baptist''s Cry','PUER NOBIS'),
(345,'Hark! A Thrilling Voice Is Sounding','MERTON'),
(346,'When All the World Was Cursed','WAS FRAG ICH NACH DER WELT'),
(347,'Comfort, Comfort Ye My People','FREU DICH SEHR'),
(348,'The King Shall Come When Morning Dawns','CONSOLATION'),
(349,'Hark the Glad Sound','CHESTERFIELD'),
(350,'Come, Thou Precious Ransom, Come','MEINEN JESUM LASS'' ICH NICHT (DARMSTADT)'),
(351,'Creator of the Stars of Night','CONDITOR ALME SIDERUM'),
(352,'Let the Earth Now Praise the Lord','NUN KOMM, DER HEIDEN HEILAND'),
(353,'Jesus Came, the Heavens Adoring','SIEH, HIER BIN ICH'),
(354,'Arise, O Christian People','AUS MEINES HERZENS GRUNDE'),
(355,'O Savior, Rend the Heavens Wide','O HEILAND, REISS DIE HIMMEL AUF'),
(356,'The Angel Gabriel from Heaven Came','GABRIEL''S MESSAGE'),
(357,'O Come, O Come, Emmanuel','VENI EMMANUEL'),
(358,'From Heaven Above to Earth I Come','VOM HIMMEL HOCH'),
(359,'Lo, How a Rose E''er Blooming','ES IST EIN ROS (Rhythmic)'),
(360,'All My Heart Again Rejoices','FROHLICH SOLL MEIN HERZE SPRINGEN'),
(361,'O Little Town of Bethlehem','ST. LOUIS'),
(362,'O Sing of Christ','FOREST GREEN'),
(363,'Silent Night, Holy Night','STILLE NACHT'),
(364,'Away in a Manger','AWAY IN A MANGER'),
(365,'Away in a Manger','CRADLE SONG'),
(366,'It Came upon the Midnight Clear','CAROL'),
(367,'Angels from the Realms of Glory','REGENT SQUARE'),
(368,'Angels We Have Heard on High','GLORIA'),
(369,'Where Shepherds Lately Knelt','MANGER SONG'),
(370,'What Child Is This','GREENSLEEVES'),
(371,'Let Our Gladness Banish Sadness','CAS RADOSTI'),
(372,'O Jesus Christ, Thy Manger Is','IN PARADISUM'),
(373,'See amid the Winter''s Snow','HUMILTY'),
(374,'Gentle Mary Laid Her Child','TEMPUS ADEST FLORIDUM'),
(375,'Come, Your Hearts and Voices Raising','QUEM PASTORES'),
(376,'Once in Royal David''s City','IRBY'),
(377,'On Christmas Night All Christians Sing','SUSSEX CAROL'),
(378,'Break Forth, O Beauteous Heavenly Light','ERMUNTRE DICH'),
(379,'O Come, All Ye Faithful','ADESTE FIDELIS'),
(380,'Hark! The Herald Angels Sing','MENDELSSOHN'),
(381,'Let Our Gladness Have No End','NARODIL SE KRISTUS PAN'),
(382,'We Praise You, Jesus, at Your Birth','GELOBET SEIST DU'),
(383,'A Great and Mighty Wonder','ES IST EIN ROS (Isorhythmic)'),
(384,'Of the Father''s Love Begotten','DIVINUM MYSTERIUM'),
(385,'From East to West','VOM HIMMEL HOCH'),
(386,'Now Sing We, Now Rejoice','IN DULCI JUBILO'),
(387,'Joy to the World','ANTIOCH'),
(388,'Go Tell It on the Mountain','GO TELL IT'),
(389,'Let All Together Praise Our God','LOBT GOTT, IHR CHRISTEN'),
(390,'Let Us All with Gladsome Voice','LASST UNS ALLE'),
(391,'Rejoice, Rejoice This Happy Morn','WIE SCHON LEUCHTET'),
(392,'God Loves Me Dearly','GOTT IST DIE LIEBE'),
(393,'Infant Holy, Infant Lowly','W ZLOBIE LEZY'),
(394,'Songs of Thankfulness and Praise','ST.GEORGE''S, WINDSOR'),
(395,'O Morning Star, How Fair and Bright','WIE SCHON LEUCHTET'),
(396,'Arise and Shine in Splendor','O WELT, ICH MUSS DICH LASSEN'),
(397,'As with Gladness Men of Old','DIX'),
(398,'Hail to the Lord''s Anointed','FREUT EUCH, IHR LIEBEN'),
(399,'The Star Proclaims the King Is Here','WO GOTT ZUM HAUS'),
(400,'Brightest and Best of the Stars of the Morning','MORNING STAR'),
(401,'From God the Father, Virgin-Born','DEUS TUORUM MILITUM'),
(402,'The Only Son from Heaven','HERR CHRIST, DER EINIG GOTTS SOHN'),
(403,'O Savior of Our Fallen Race','PUTNAM'),
(404,'Jesus, Once with Sinners Numbered','MISSISSIPPI'),
(405,'To Jordan''s River Came Our Lord','WINCHESTER NEW'),
(406,'To Jordan Came the Christ, Our Lord','CHRIST, UNSER HERR'),
(407,'To Jordan Came the Christ, Our Lord','ELVET BANKS'),
(408,'Come, Join in Cana''s Feast','FRANCONIA'),
(409,'Hail, O Source of Every Blessing','O DURCHBRECHER'),
(410,'Within the Father''s House','FRANCONIA'),
(411,'I Want to Walk as a Child of the Light','HOUSTON'),
(412,'The People That in Darkness Sat','LOBT GOTT, IHR CHRISTEN'),
(413,'O Wondrous Type! O Vision Fair','DEO GRACIAS'),
(414,'''Tis Good, Lord, to Be Here','POTSDAM'),
(415,'Jesus on the Mountain Peak','SEWARD'),
(416,'Swiftly Pass the Clouds of Glory','LOVE''S LIGHT'),
(417,'Alleluia, Song of Gladness','LAUDA ANIMA'),
(418,'O Lord, throughout These Forty Days','CAITHNESS'),
(419,'Savior, When in Dust to Thee','ABERYSTWYTH'),
(420,'Christ, the Life of All the Living','JESU, MEINES LEBENS LEBEN'),
(421,'Jesus, Grant That Balm and Healing','DER AM KREUZ'),
(422,'On My Heart Imprint Your Image','DER AM KREUZ'),
(423,'Jesus, Refuge of the Weary','O DU LIEBE MEINER LIEBE'),
(424,'O Christ, You Walked the Road','SOUTHWELL'),
(425,'When I Survey the Wondrous Cross','HAMBURG'),
(426,'When I Survey the Wondrous Cross','ROCKINGHAM OLD'),
(427,'In the Cross of Christ I Glory','RATHBUN'),
(428,'Cross of Jesus, Cross of Sorrow','CROSS OF JESUS'),
(429,'We Sing the Praise of Him Who Died','WINDHAM'),
(430,'My Song Is Love Unknown','LOVE UNKNOWN'),
(431,'Not All the Blood of Beasts','SOUTHWELL'),
(432,'In Silent Pain the Eternal Son','REALITY'),
(433,'Glory Be to Jesus','WEM IN LEIDENSTAGEN'),
(434,'Lamb of God, Pure and Holy','O LAMM FOTTES, UNSCHULDIG'),
(435,'Come to Calvary''s Holy Mountain','NAAR MIT OIE'),
(436,'Go to Dark Gethsemane','GETHSEMANE'),
(437,'Alas! And Did My Savior Bleed','MARTYDOM'),
(438,'A Lamb Goes Uncomplaining Forth','AN WASSERFLUSSEN BABYLON'),
(439,'O Dearest Hesus, What Law Hast Thou Broken','HERZLIEBSTER JESU'),
(440,'Jesus, I Will Ponder Now','JESU KREUZ, LEIDEN UND PEIN'),
(441,'Ride On, Ride On in Majesty','WINCHESTER NEW'),
(442,'All Glory, Laud, and Honor','VALET WILL ICH DIR GEBEN'),
(443,'Hosanna, Loud Hosanna','ELLACOMBE'),
(444,'No Tramp of Soldiers'' Marching Feet','KINGSFOLD'),
(445,'When You Woke That Thursday Morning','JOYOUS LIGHT'),
(446,'Jesus, Greatest at the Table','NEW MALDEN'),
(447,'Jesus, in Your Dying Woes','SEPTEM VERBA'),
(448,'O Darkest Woe','O TRAURIGKEIT'),
(449,'O Sacred Head, Now Wounded','HERZLICH TUT MICH VERLANGEN (Isorhythmic)'),
(450,'O Sacred Head, Now Wounded','HERZLICH TUT MICH VERLANGEN (Rhythmic)'),
(451,'Stricken, Smitten, and Afflicted','O MEIN JESU, ICH MUSS STERBEN'),
(452,'O Perfect Life of Love','SOUTHWELL'),
(453,'Upon the Cross Extended','O WELT, ICH MUSS DICH LASSEN'),
(454,'Sing, My Tongue, the Glorious Battle','FORTUNATUS NEW'),
(455,'The Royal Banners Forward Go','VEXILLA REGIS NOVA'),
(456,'Were You There','WERE YOU THERE'),
(457,'Jesus Christ Is Risen Today','EASTER HYMN'),
(458,'Christ Jesus Lay in Death''s Strong Bands','CHRIST LAG IN TODESBANDEN'),
(459,'Christ Is Arisen','CHRIST IST ERSTANDEN'),
(460,'Christians, to the Paschal Victim','VICTIMAE PASCHALI'),
(461,'I Know That My Redeemer Lives','DUKE STREET'),
(462,'All the Earth with Joy Is Sounding','MICHAEL'),
(463,'Christ the Lord Is Risen Today; Alleluia','LLANFAIR'),
(464,'The Strife Is O''er, the Battle Done','VICTORY'),
(465,'Now All the Vault of Heaven Resounds','LASST UNS ERFREUEN'),
(466,'Christ Has Arisen, Alleluia','MFURAHINI HALELUYA'),
(467,'Awake, My Heart, with Gladness','AUF, AUF, MEIN HERZ'),
(468,'I Am Content! My Jesus Ever Lives','ES IST GENUG'),
(469,'Christ the Lord Is Risen Today','ORIENTIS PARTIBUS'),
(470,'O Sons and Daughters of the King','GELOBT SEI GOTT'),
(471,'O Sons and Daughters of the King','O FILII ET FILIAE'),
(472,'These Things Did Thomas Count as Real','REALITER'),
(473,'Our Paschal Lamb, That Sets Us Free','REGION THREE'),
(474,'Alleluia! Jesus Is Risen','EARTH AND ALL STARS'),
(475,'Good Christian Friends, Rejoice and Sing','GELOBT SEI GOTT'),
(476,'Who Are You Who Walk in Sorrow','JEFFERSON'),
(477,'Alleluia, Alleluia! Hearts to Heaven','HYMN TO JOY'),
(478,'The Day of Resurrection','LANCASHIRE'),
(479,'Christ Is Risen, Christ Is Living','CENTRAL'),
(480,'He''s Risen, He''s Risen','WALTHER'),
(481,'Scatter the Darkness, Break the Gloom','BESANCON'),
(482,'This Joyful Eastertide','VREUCHTEN'),
(483,'With High Delight Let Us Unite','MIT FREUDEN ZART'),
(484,'Make Songs of Joy','ZPIVEJMEZ VSICKNI VESELE'),
(485,'Long before the World Is Waking','ALL SAINTS'),
(486,'If Christ Had Not Been Raised from Death','UNION CITY'),
(487,'Come, You Faithful, Raise the Strain','GAUDEAMUS PARITER'),
(488,'He Is Arisen! Glorious Word','WIE SCHON LEUCHTET'),
(489,'Hail Thee, Festival Day','SALVE FESTA DIES'),
(490,'Jesus Lives! The Victory''s Won','JESUS, MEINE ZUVERSICHT'),
(491,'Up through Endless Ranks of Angels','ASCENDED TRIUMPH'),
(492,'On Christ''s Ascension I Now Build','NUN FREUT EUCH'),
(493,'A Hymn of Glory Let Us Sing','LASST UNS ERFREUEN'),
(494,'See, the Lord Ascends in Triumph','REX GLORIAE'),
(495,'Look, Ye Saints, the Sight is Glorious','BRYN CALFARIA'),
(496,'Holy Spirit, Light Divine','SONG 13'),
(497,'Come, Holy Ghost, God and Lord','KOMM, HEILIGER GEIST, HERRE GOTT'),
(498,'Come, Holy Ghost, Creator Blest','KOMM, GOTT SCHOPFER'),
(499,'Come, Holy Ghost, Creator Blest','VENI CREATOR SPIRITUS'),
(500,'Creator Spirit, by Whose Aid','ALL EHR UND LOB'),
(501,'Come Down, O Love Divine','DOWN AMPNEY'),
(502,'Holy Spirit, the Dove Sent from Heaven','SANTO ESPIRITU'),
(503,'O Day Full of Grace','DEN SIGNEDE DAG'),
(504,'Father Most Holy','CHRISTE SANCTORUM'),
(505,'Triune God, Be Thou Our Stay','GOTT DER VATER, WOHN UNS BEI'),
(506,'Glory Be to God the Father','WORCESTER'),
(507,'Holy, Holy, Holy','NICAEA'),
(508,'The Day Is Surely Drawing Near','ES IST GEWISSLICH'),
(509,'Christ Is Surely Coming','KING''S WESTON'),
(510,'A Multitude Comes from the East and the West','DER MANGE SKAL KOMME'),
(511,'Herald, Sound the Note of Judgment','NEW MALDEN'),
(512,'At the Name of Jesus','KING''S WESTON'),
(513,'The Clouds of Judgment Gather','LLANGLOFFAN'),
(514,'The Bridegroom Soon Will Call Us','ACH GOTT VON HIMMELREICHE'),
(515,'Rejoice, Rejoice, Believers','HAF TRONES LAMPA FARDIG'),
(516,'Wake, Awake, for Night is Flying','WACHET AUF'),
(517,'By All Your Saints in Warfare','KING''S LYNN'),
(518,'By All Your Saints in Warfare','KING''S LYNN'),
(519,'In His Temple Now Behold Him','WESTMINSTER ABBEY'),
(520,'Stars of the Morning, So Gloriously Bright','O QUANTA QUALIA'),
(521,'Christ, the Lord of Hosts, Unshaken','FORTUNATUS NEW'),
(522,'Lord God, to Thee We Give All Praise','ERHALT UNS, HERR'),
(523,'O Word of God Incarnate','MUNICH'),
(524,'How Sweet the Name of Jesus Sounds','ST. PETER'),
(525,'Crown Him with Many Crowns','DIADEMATA'),
(526,'You Are the Way; through You Alone','DUNDEE'),
(527,'O Savior, Precious Savior','ANGEL''S STORY'),
(528,'Oh, for a Thousand Tongues to Sing','AZMON'),
(529,'Since Our Great High Priest, Christ Jesus','ALL SAINTS'),
(530,'No Temple Now, No Gift of Price','KIRKWOOD'),
(531,'Hail, Thou Once Despised Jesus','O DURCHBRECHER'),
(532,'The Head That Once Was Crowned with Thorns','ST. MAGNUS'),
(533,'Jesus Has Come and Brings Pleasure','JESUS IST KOMMEN, GRUND EWIGER FREUDE'),
(534,'Lord, Enthroned in Heavenly Splendor','BRYN CALFARIA'),
(535,'How Wide the Love of Christ','SWABIA'),
(536,'One Thing''s Needful','EINS IST NOT'),
(537,'Beautiful Savior','SCHONSTER HERR JESU'),
(538,'Praise Be to Christ','O GROSSER GOTT'),
(539,'Christ Is the World''s Redeemer','MOVILLE'),
(540,'Christ, the Word of God Incarnate','HOLY MANNA'),
(541,'"Away from Us!" the Demon Cried','MCKEE'),
(542,'When I Behold Jesus Christ','MIN AYNET FIQIR NEW'),
(543,'What Wondrous Love Is This','WONDROUS LOVE'),
(544,'O Love, How Deep','DEO GRACIAS'),
(545,'Word of God, Come Down on Earth','LIEBSTER JESU, WIR SIND HIER'),
(546,'O Jesus So Sweet, O Jesus So Mild','O JESULEIN SUSS'),
(547,'The Lamb','WINTER'),
(548,'Thanks to Thee, O Christ, Victorious','WERDE MUNTER'),
(549,'All Hail the Power of Jesus'' Name','CORONATION'),
(550,'Lamb O God','LAMB OF GOD'),
(551,'When to Our World the Savior Came','CANONBURY'),
(552,'O Christ, Who Shared Our Mortal Live','LORD OF LIFE'),
(553,'O Christ, Our Hope, Our Heart''s Desire','ICH SINGE DIR'),
(554,'O Jesus, King Most Wonderful','ST. AGNES'),
(555,'Salvation unto Us Has Come','ES IST DAS HEIL'),
(556,'Dear Christians, One and All, Rejoice','NUN FREUT EUCH'),
(557,'Seek Where You May to Find a Way','SUCH, WER DA WILL'),
(558,'Not unto Us','NOT UNTO US'),
(559,'Oh, How Great is Your Compassion','ACH, WAS SOLL ICH SUNDER MACHEN'),
(560,'Drawn to the Cross, Which Thou Hast Blessed','DUNSTAN'),
(561,'The Tree of Life','TREE OF LIFE'),
(562,'All Mankind Fell in Adam''s Fall','WENN WIR IN HOCHSTEN NOTEN SEIN'),
(563,'Jesus, Thy Blood and Righteousness','ST. CRISPIN'),
(564,'Christ Sits at God''s Right Hand','YIGDAL'),
(565,'Thy Works, Not Mine, O Christ','ST. JOHN'),
(566,'By Grace I''m Saved','O DASS ICH TAUSEND ZUNGEN HATTE (DRETZEL)'),
(567,'Not What These Hands Have Done','ENERGY'),
(568,'If Your Beloved Son, O God','NUN FREUT EUCH'),
(569,'In Adam We Have All Been One','THE SAINTS'' DELIGHT'),
(570,'Just as I Am, without One Plea','WOODWORTH'),
(571,'God Loved the World So That He Gave','ST. CRISPIN'),
(572,'In the Shattered Bliss of Eden','RUSTINGTON'),
(573,'Lord, ''Tis Not That I Did Choose Thee','O DU LIEBE MEINER LIEBE'),
(574,'Before the Throne of God Above','DUNEDIN'),
(575,'My Hope Is Built on Nothing Less','MAGDALEN'),
(576,'My Hope Is Built on Nothing Less','THE SOLID ROCK'),
(577,'Almighty God, Your Word is Cast','ST. FLAVIAN'),
(578,'Thy Strong Word','EBENEZER'),
(579,'The Law of God Is Good and Wise','ERHALT UNS, HERR'),
(580,'The Gospel Shows the Father''s Grace','HERR JESU CHRIST, DICH ZU UNS WEND'),
(581,'These Are the Holy Ten Commands','IN GOTTES NAMEN FAHREN WIR'),
(582,'God''s Word Is Our Great Heritage','REUTER'),
(583,'God Has Spoken by His Prophets','REX GLORIAE'),
(584,'Faith and Truth and Life Bestowing','HOLY MANNA'),
(585,'Lord Jesus Christ, with Us Abide','ACH BLEIB BEI UNS'),
(586,'Preach You the Word','O HEILAND, REISS DIE HIMMEL AUF'),
(587,'I Know My Faith Is Founded','NUN LOB, MEIN SEEL'),
(588,'Jesus Loves Me','JESUS LOVES ME'),
(589,'Speak, O Lord, Your Servant Listens','WERDE MUNTER'),
(590,'Baptized into Your Name Most Holy','O DASS ICH TAUSEND ZUNGEN HATTE (DRETZEL)'),
(591,'This Is the Spirit''s Entry Now','DAMASCUS ROAD'),
(592,'Dearest Jesus, We Are Here','LIEBSTER JESU, WIR SIND HIER'),
(593,'See This Wonder in the Making','TRYGGARE KAN INGEN VARA'),
(594,'God''s Own Child, I Gladly Say It','BACHOFEN'),
(595,'O Blessed Spring','O WALY WALY'),
(596,'All Christians Who Have Been Baptized','NUN FREUT EUCH'),
(597,'Water, Blood, and Spirit Crying','FILTER'),
(598,'Once in the Blest Baptismal Waters','WER WEISS, WIE NAHE'),
(599,'O Gracious Lord, with Love Draw Near','DUNEDIN'),
(600,'Mark How the Lamb of God''s Self-Offering','RENDEZ A DIEU'),
(601,'All Who Believe and Are Baptized','ES IST DAS HEIL'),
(602,'The Gifts Christ Freely Gives','DENBY'),
(603,'We Know That Christ Is Raised','ENGELBERG'),
(604,'I Bind unto Myself Today','ST. PATRICK''S BREASTPLATE'),
(605,'Father Welcomes','FATHER WELCOMES'),
(606,'I Lay My Sins on Jesus','MUNICH'),
(607,'From Depths of Woe I Cry to Thee','AUS TIEFER NOT'),
(608,'Lord, to You I Make Confession','HERR, ICH HABE MISSGEHANDELT'),
(609,'Jesus Sinners Doth Receive','MEINEN JESUM LASS'' ICH NICHT (DARMSTADT)'),
(610,'Lord Jesus, Think on Me','SOUTHWELL'),
(611,'Chief of Sinners Though I Be','GETHSEMANE'),
(612,'As Rebels, Lord, Who Foolishly Have Wandered','WELCOME'),
(613,'To Thee, Omniscient Lord of All','VATER UNSER'),
(614,'"As Surely as I Live," God Said','ST. LUKE'),
(615,'When in the Hour of Deepest Need','WENN WIR IN HOCHSTEN NOTEN SEIN'),
(616,'Baptismal Waters Cover Me','GOTTLOB, ES GEHT NUNMEHR ZU ENDE'),
(617,'O Lord, We Praise Thee','GOTT SEI GELOBET UND GEBENEDEIET'),
(618,'I Come, O Savior, to Thy Table','ICH STERBE TAGLICH'),
(619,'Thy Body, Given for Me, O Savior','ICH STERBE TAGLICH'),
(620,'Jesus Comes Today with Healing','ALLES IST AN GOTTES SEGEN'),
(621,'Let All Mortal Flesh Keep Silence','PICARDY'),
(622,'Lord Jesus Christ, You Have Prepared','DU LEBENSBROT, HERR JESU CHRIST'),
(623,'Lord Jesus Christ, We Humbly Pray','HERR JESU CHRIST, DICH ZU UNS WEND'),
(624,'The Infant Priest Was Holy Born','ROCKINGHAM OLD'),
(625,'Lord Jesus Christ, Life-Giving Bread','HERR, WIE DU WILLST'),
(626,'Come Let Us Eat','A VA DE'),
(627,'Jesus Christ, Our Blessed Savior','JESUS CHRISTUS, UNSER HEILAND'),
(628,'Your Table I Approach','ST. MICHAEL'),
(629,'What Is This Bread','PREPARATION'),
(630,'Now, My Tongue, the Mystery Telling','GRAFTON'),
(631,'Here, O My Lord, I See Thee Face to Face','FARLEY CASTLE'),
(632,'O Jesus, Blessed Lord, to Thee','OLD HUNDREDTH'),
(633,'At the Lamb''s High Feast We Sing','SONNE DER GERECHTIGKEIT'),
(634,'The Death of Jesus Christ, Our Lord','GOTTLOB, ES GEHT NUNMEHR ZU ENDE'),
(635,'O Gracious Lord, I Firmly Am Believing','OH BUEN JESUS'),
(636,'Soul, Adorn Yourself with Gladness','SCHMUCKE DICH'),
(637,'Draw near and Take the Body of the Lord','OLD 124TH, abbr.'),
(638,'Eat This Bread','EAT THIS BREAD'),
(639,'Wide Open Stand the Gates','JERUSALEM, DU HOCHGEBAUTE STADT'),
(640,'Thee We Adore, O Hidden Savior','ADORO TE DEVOTE'),
(641,'You Satisfy the Hungry Heart','BICENTENNIAL'),
(642,'O Living Bread from Heaven','ACH GOTT VOM HIMMELREICHE'),
(643,'Sent Forth by God''s Blessing','THE ASH GROVE'),
(644,'The Church''s One Foundation','AURELIA'),
(645,'Built on the Rock','KIRKEN DEN ER ET GAMMELT HUS'),
(646,'Church of God, Elect and Glorious','ABBOT''S LEIGH'),
(647,'Lord Jesus Christ, the Church''s Head','REUTER'),
(648,'Glorious Things of You Are Spoken','AUSTRIA'),
(649,'Blest Be the Tie That Binds','BOYLSTON'),
(650,'Holy Spirit, Ever Dwelling','IN BABILONE'),
(651,'I Love Your Kingdom, Lord','ST. THOMAS'),
(652,'Father, We Thank Thee','RENDEZ A DIEU'),
(653,'In Christ There Is No East of West','MCKEE'),
(654,'Your Kingdom, O God, Is My Glorious Treasure','GLORIOUS TREASURE'),
(655,'Lord, Keep Us Steadfast in Your Word','ERHALT UNS, HERR'),
(656,'A Mighty Fortress Is Our God','EIN FESTE BURG (Rhythmic)'),
(657,'A Mighty Fortress Is Our God','EIN FESTE BURG (Isorhythmic)'),
(658,'Preserve Your Word, O Savior','MUNICH'),
(659,'Lord of Our Life','ISTE CONFESSOR'),
(660,'Stand Up, Stand Up for Jesus','WEBB'),
(661,'The Son of God Goes Forth to War','ALL SAINTS NEW'),
(662,'Onward, Christian Soldiers','ST. GERTRUDE'),
(663,'Rise, My Soul, to Watch and Pray','STRAF MICH NICHT'),
(664,'Fight the Good Fight','MENDON'),
(665,'Be Strong in the Lord','LAUDATE DOMINUM'),
(666,'O Little Flock, Fear Not the Foe','KOMMT HER ZU MIR'),
(667,'Saints, See the Cloud of Witnesses','WOJTKIEWIECZ'),
(668,'Rise! To Arms! With Prayer Employ You','WACHET AUF'),
(669,'Come, We That Love the Lord','MARCHING TO ZION'),
(670,'Ye Watchers and Ye Holy Ones','LASST UNS ERFREUEN'),
(671,'Sing With All the Saints in Glory','MISSISSIPPI'),
(672,'Jerusalem the Golden','EWING'),
(673,'Jerusalem, My Happy Home','LAND OF REST'),
(674,'Jerusalem, O City Fair and High','JERUSALEM, DU HOCHGEBAUTE STADT'),
(675,'Oh, What Their Joy','O QUANTA QUALIA'),
(676,'Behold a Host, Arrayed in White','DEN STORE HVIDE FLOK'),
(677,'For All the Saints','SINE NOMINE'),
(678,'We Sing for All the Unsung Saints','ALL SAINTS NEW'),
(679,'Oh, How Blest Are They','O WIE SELIG'),
(680,'Thine the Amen, Thine the Praise','THINE'),
(681,'Send, O Lord, Your Holy Spirit','WERDE MUNTER'),
(682,'God of the Prophets, Bless the Prophets'' Sons','OLD 124TH, abbr.'),
(683,'Jesus, Thy Boundless Love to Me','RYBURN'),
(684,'Come unto Me, Ye Weary','ANTHES'),
(685,'Let Us Ever Walk with Jesus','LASSET UNS MIT JESU ZIEHEN'),
(686,'Come, Thou Fount of Every Blessing','NETTLETON'),
(687,'Thine Forever, God of Love','VIENNA'),
(688,'"Come, Follow Me," the Savior Spake','MACHS MIT MIR, GOTT'),
(689,'Let Me Be Thine Forever','LOB GOTT GETROST MIT SINGEN'),
(690,'Hope of the World','EIRENE'),
(691,'Fruitful Trees, the Spirit''s Sowing','DOROTHY'),
(692,'Praise to You and Adoration','FREU DICH SEHR'),
(693,'O Holy Spirit, Grant Us Grace','ES IST GEWISSLICH'),
(694,'Thee Will I Love, My Strength, My Tower','ICH WILL DICH LIEBEN'),
(695,'Not for tongues of Heaven''s Angels','BRIDEGROOM'),
(696,'O God, My Faithful God','O GOTT, DU FROMMER GOTT'),
(697,'Awake, O Sleeper, Rise from Death','AZMON'),
(698,'May We Thy Precepts, Lord, Fulfill','MERIBAH'),
(699,'I Heard the Voice of Jesus Say','SARAH-ELIZABETH'),
(700,'Love Divine, All Loves Excelling','HYFRYDOL'),
(701,'Draw us to Thee','ACH GOTT UND HERR'),
(702,'My Faith Looks Up to Thee','OLIVET'),
(703,'How Can I Thank You, Lord','O GOTT, DU FROMMER GOTT'),
(704,'Renew Me, O Eternal Light','HERR JESU CHRIST, MEINS'),
(705,'The Man Is Ever Blessed','ST. MICHAEL'),
(706,'Love in Christ Is Strong and Living','DOROTHY'),
(707,'Oh, That the Lord Would Guide my Ways','EVAN'),
(708,'Lord, Thee I Love with All My Heart','HERZLICH LIEB'),
(709,'The King of Love My Shepherd Is','ST. COLUMBA'),
(710,'The Lord''s My Shepherd, I''ll Not Want','BELMONT'),
(711,'Savior, like a Shepherd Lead Us','BRADBURY'),
(712,'Seek Ye First','SEEK YE FIRST'),
(713,'From God Can Nothing Move Me','VON GOTT WILL ICH NICHT LASSEN'),
(714,'Who Trusts in God a Strong Abode','WAS MEIN GOTT WILL (Rhythmic)'),
(715,'Jesus, Savior, Pilot Me','PILOT'),
(716,'I Walk in Danger All the Way','DER LIEBEN SONNE LICHT UND PRACHT'),
(717,'Eternal Father, Strong to Save','MELITA'),
(718,'Jesus, Lead Thou On','SEELENBRAUTIGAM'),
(719,'I Leave All things to God''s Direction','WER NUR DEN LIEBEN GOTT'),
(720,'We Walk by Faith and Not by Sight','SHANTI'),
(721,'Lead Me, Guide Me','LEAD ME'),
(722,'Lord, Take My Hand and Lead Me','SO NIMM DENN MEINE HANDE'),
(723,'The Lord Is My Light','EL SENOR ES MI LUZ'),
(724,'If God Himself Be for Me','IST GOTT FUR MICH'),
(725,'Children of the Heavenly Father','TRYGGARE KAN INGEN VARA'),
(726,'Evening and Morning','DIE GULDNE SONNE'),
(727,'On Eagles'' Wings','ON EAGLES'' WINGS'),
(728,'How Firm a Foundation','FOUNDATION'),
(729,'I Am Trusting Thee, Lord Jesus','STEPHANOS'),
(730,'What Is the World to Me','WAS FRAG ICH NACH DER WELT'),
(731,'O God, Forsake Me Not','O GOTT, DU FROMMER GOTT'),
(732,'All Depends on Our Possessing','ALLES IST AN GOTTES SEGEN'),
(733,'O God, Our Help in Ages Past','ST. ANNE'),
(734,'I Trust, O Lord, Your Holy Name','IN DICH HAB ICH GEHOFFET'),
(735,'Have No Fear, Little Flock','LITTLE FLOCK'),
(736,'Consider How the Birds Above','NORTHCROFT'),
(737,'Rejoice, My Heart, Be Glad and Sing','ICH SINGE DIR'),
(738,'Lord of All Hopefulness','SLANE'),
(739,'Precious Lord, Take My Hand','PRECIOUS LORD'),
(740,'I Am Jesus'' Little Lamb','WEIL ICH JESU SCHALEIN BIN'),
(741,'Jesus Christ, My Sure Defense','JESUS, MEINE ZUVERSICHT'),
(742,'For me to Live Is Jesus','CHRISTUS, DER IST MEIN LEBEN'),
(743,'Jesus, Priceless Treasure','JESU, MEINE FREUDE'),
(744,'Amazing Grace','NEW BRITAIN'),
(745,'In God, My Faithful God','AUF MEINEN LIEBEN GOTT'),
(746,'Through Jesus'' Blood and Merit','LOB GOTT GETROST MIT SINGEN'),
(747,'No Saint on Earth Lives Life to Self Alone','SONG 1'),
(748,'I''m But a Stranger Here','HEAVEN IS MY HOME'),
(749,'There Is a Balm in Gilead','BALM IN GILEAD'),
(750,'If Thou But Trust in God to Guide Thee','WER NUR DEN LIEBEN GOTT'),
(751,'O God of Love, O King of Peace','NYLUNDA'),
(752,'Be Still, My Soul','FINLANDIA'),
(753,'All for Christ I Have Forsaken','RESTORATION'),
(754,'Entrust Your Days and Burdens','SUFFICIENTIA'),
(755,'In the Very Midst of Life','MITTEN WIR IM LEBEN SIND'),
(756,'Why should Cross and Trial Grieve me','WARUM SOLLT ICH MICH DENN GRAMEN'),
(757,'Lord, It Belongs Not to My Care','ST. FULBERT'),
(758,'The Will of God Is Always Best','WAS MEIN GOTT WILL (Isorhythmic)'),
(759,'This Body in the Grave We Lay','NUN LASST UNS DEN LEIB'),
(760,'What God Ordains Is Always Good','WAS GOTT TUT'),
(761,'Rock of Ages, Cleft for Me','TOPLADY'),
(762,'There is a Time for Everything','ST. PETER''S NORWALK'),
(763,'When Peace Like a River','IT IS WELL'),
(764,'When Aimless Violence Takes Those We Love','SURSUM CORDA'),
(765,'God Moves in a Mysterious Way','DUNDEE'),
(766,'Our Father, Who from Heaven Above','VATER UNSER'),
(767,'Jesus, Remember Me','REMEMBER ME'),
(768,'To God the Holy Spirit Let Us Pray','NUN BITTEN WIR'),
(769,'Eternal Spirit of the Living Christ','FARLEY CASTLE'),
(770,'What a Friend We Have in Jesus','CONVERSE'),
(771,'Be Still, My Soul, before the Lord','SHANTI'),
(772,'In Holy Conversation','BRED DINA VIDA VINGAR'),
(773,'Hear Us, Father, When We Pray','MORGENGLANZ DER EWIGKEIT'),
(774,'Feed Thy Children, God Most Holy','SCHMUCKE DICH'),
(775,'Be Present at Our Table, Lord','OLD HUNDREDTH'),
(776,'Come, Lord Jesus, Be Our Guest','KOMM, HERR JESU'),
(777,'Grant Peace, We Pray, in Mercy, Lord','MENDELSSOHN DA PACEM'),
(778,'Grant Peace, We Pray, in Mercy, Lord','VERLEIH UNS FRIEDEN'),
(779,'Come, My Soul, with Every Care','VIENNA'),
(780,'O Lord, Hear My Prayer','HEAR MY PRAYER'),
(781,'We Give Thee But Thine Own','ENERGY'),
(782,'Gracious God, You Send Great Blessings','HOLY MANNA'),
(783,'Take My Life and Let It Be','PATMOS'),
(784,'Take My Life and Let It Be','HENDON'),
(785,'We Praise You, O God','KREMSER'),
(786,'Lord of All Good','FARLEY CASTLE'),
(787,'The Temple Rang with Golden Coins','ST. FLAVIAN'),
(788,'Forgive Us, Lord, for Shallow Thankfulness','SURSUM CORDA'),
(789,'Praise and Thanksgiving','BUNESSAN'),
(790,'Praise to the Lord, the Almighty','LOBE DEN HERREN'),
(791,'All People That on Earth Do Dwell','OLD HUNDREDTH'),
(792,'New Songs of Celebration Render','RENDEZ A DIEU'),
(793,'Praise, My Soul, the King of Heaven','LAUDA ANIMA'),
(794,'The Lord, My God, Be Praised','NUN DANKET ALLE GOTT'),
(795,'Voices Raised to You We Offer','SONG OF PRAISE'),
(796,'When in Our Music God Is Glorified','ENGELBERG'),
(797,'Praise the Almighty','LOBE DEN HERREN, O MEINE SEELE'),
(798,'The God of Abraham Praise','YIGDAL'),
(799,'Alabare - I','ALABARE'),
(800,'Alabare - II','ALABARE'),
(801,'How Great Thou Art','O STORE GUD'),
(802,'Immortal, Invisible, God Only Wise','ST. DENIO'),
(803,'Joyful Joyful We Adore Thee','HYMN TO JOY'),
(804,'O Worship the King','HANOVER'),
(805,'Praise God, from Whom All Blessings Flow','OLD HUNDREDTH'),
(806,'Give Thanks with a Grateful Heart','GIVE THANKS'),
(807,'When Morning Gilds the Skies','LAUDES DOMINI'),
(808,'O Sing to the Lord','CANTAD AL SENOR'),
(809,'Great Is Thy Faithfulness','FAITHFULNESS'),
(810,'O God of God, O Light of Light','O GROSSER GOTT'),
(811,'Oh, That I Had a Thousand Voices','O DASS ICH TAUSEND ZUNGEN HATTE (KONIG)'),
(812,'Come, Let Us Join Our Cheerful Songs','NUN DANKET ALL'),
(813,'Rejoice, O Pilgrim Throng','MARION'),
(814,'O Bless the Lord, My Soul','ST. THOMAS'),
(815,'All Praise to Thee, for Thou, O King Divine','ENGELBERG'),
(816,'From All that Dwell Below the Skies','LASST UNS ERFREUEN'),
(817,'Earth and All Stars','EARTH AND ALL STARS'),
(818,'In Thee Is Gladness','IN DIR IST FREUDE'),
(819,'Sing Praise to God, the Highest Good','LOBT GOTT DEN HERREN, IHR'),
(820,'My Soul, Now Praise Your Maker!','NUN LOB, MEIN SEEL'),
(821,'Alleluia! Sing to Jesus','HYFRYDOL'),
(822,'Alleluia! Let Praise Ring','WIE SCHON LEUCHTET'),
(823,'May God Bestow on Us His Grace','ES WOLLE GOTT UNS GNADIG SEIN'),
(824,'May God Bestow on Us His Grace','ELVET BANKS'),
(825,'Rise, Shine, You People','WOJTKIEWIECZ'),
(826,'Hark, the Voice of Jesus Crying','GALILEAN'),
(827,'Hark, The Voice of Jesus Calling','GALILEAN'),
(828,'We Are Called to Stand Together','ASCENDED TRIUMPH'),
(829,'Christ the Eternal Lord','DIADEMATA'),
(830,'Spread the Reign of God the Lord','GOTT SEI DANK'),
(831,'"How Shall They Hear," Who Have Not Heard','ANGELUS'),
(832,'Jesus Shall Reign','DUKE STREET'),
(833,'Listen, God Is Calling','NENO LAKE MUNGU'),
(834,'O God, O Lord of Heaven and Earth','WITTENBERG NEW'),
(835,'On Galilee''s High Mountain','MISSIONARY HYMN'),
(836,'O God of Light','ATKINSON'),
(837,'Lift High the Cross','CRUCIFER'),
(838,'The Saints in Christ Are One in Every Place','WOODLANDS'),
(839,'O Christ, Our True and Only Light','O JESU CHRISTE, WAHRES LICHT'),
(840,'Christ High-Ascended, Now in Glory Seated','ISTE CONFESSOR'),
(841,'O Son of God, in Galilee','TWENTY-FOURTH'),
(842,'Son of God, Eternal Savior','IN BABILONE'),
(843,'"Forgive Our Sins as We Forgive"','DETROIT'),
(844,'Lord of All Nations, Grant Me Grace','ANGELUS'),
(845,'Where Charity and Love Prevail','TWENTY-FOURTH'),
(846,'Your Hand, O Lord, in Days of Old','KINGSFOLD'),
(847,'Christ, Our Human Likeness Sharing','GRAFTON'),
(848,'Lord, Whose Love Through Humble Service','BEACH SPRING'),
(849,'Praise the One Who Breaks the Darkness','BEACH SPRING'),
(850,'God of Grace and God of Glory','CWM RHONDDA'),
(851,'Lord of Glory, You Have Bought Us','HYFRYDOL'),
(852,'O God of Mercy, God of Might','ISLEWORTH'),
(853,'How Clear Is Our Vocation, Lord','REPTON'),
(854,'Forth in Thy Name, O Lord, I Go','LAKEWOOD'),
(855,'For All the Faithful Women','KUORTANE'),
(856,'O Christ, Who Called the Twelve','TERRA BEATA'),
(857,'Lord, Help Us Walk Your Servant Way','ST. FLAVIAN'),
(858,'O Father, All Creating','AURELIA'),
(859,'Lord, When You Came as Welcome Guest','LAND OF REST'),
(860,'Gracious Savior, Grant Your Blessing','HYFRYDOL'),
(861,'Christ Be My Leader','SLANE'),
(862,'Oh, Blest the House','WO GOTT ZUM HAUS'),
(863,'Our Father, by Whose Name','RHOSYMEDRE'),
(864,'Shepherd of Tender Youth','ITALIAN HYMN'),
(865,'Lord, Help Us Ever to Retain','HERR JESU CHRIST, MEINS'),
(866,'Lord Jesus Christ, the Children''s Friend','WAREHAM'),
(867,'Let Children Hear the Mighty Deeds','NUN DANKET ALL'),
(868,'Awake, My Soul, and with the Sun','MORNING HYMN'),
(869,'With the Lord Begin Your Task','FANG DEIN WERK'),
(870,'Now That the daylight fills the sky','LAUREL'),
(871,'Greet the Rising Sun','LE P''ING'),
(872,'Come, Thou Bright and Morning Star','MORGENGLANZ DER EWIGKEIT'),
(873,'Christ, Whose Glory Fills the Skies','RATISBON'),
(874,'O Splendor of God''s Glory Bright','PUTNAM'),
(875,'Father, We Praise Thee','CHRISTE SANCTORUM'),
(876,'O Blessed, Holy Trinity','O HEILIGE DREIFALTIGKEIT'),
(877,'God, Who Made the Earth and Heaven','AR HYD Y NOS'),
(878,'Abide with Me','EVENTIDE'),
(879,'Stay with Us','STAY WITH US'),
(880,'Now Rest beneath Night''s Shadow','O WELT, ICH MUSS DICH LASSEN'),
(881,'Christ, Mighty Savior','INNISFREE FARM'),
(882,'O Christ, Who Art the Light and Day','CONDITOR ALME SIDERUM'),
(883,'All Praise to Thee, My God, This Night','TALLIS'' CANON'),
(884,'Lord, Support Us All Day Long','GWALCHMAI'),
(885,'I Lie, O Lord, within Your Care','ICH LIEGE, HERR IN DEINER HUT'),
(886,'The Day Thou Gavest','ST. CLEMENT'),
(887,'Now the Light Has Gone Away','MUDE BIN ICH'),
(888,'O Gladsome Light, O Grace','NUNC DIMITTIS'),
(889,'Before the Ending of the Day','JAM LUCIS'),
(890,'O Blessed Light, O Trinity','O HEILIGE DREIFALTIGKEIT'),
(891,'O Light, Whose Splendor','ST. CLEMENT'),
(892,'Come, Ye Thankful People, Come','ST. GEORGE''S WINDSOR'),
(893,'Sing to the Lord of Harvest','WIE LIEBLICH IST DER MAIEN'),
(894,'For the Fruits of His Creation','AR HYD Y NOS'),
(895,'Now Thank We All Our God','NUN DANKET ALLE GOTT'),
(896,'Now Greet the Swiftly Changing Year','SIXTH NIGHT'),
(897,'O Rejoice, Ye Christians, Loudly','FREUET EUCH, IHR CHRISTEN'),
(898,'The Ancient Law Departs','POTSDAM'),
(899,'Across the Sky the Shades of Night','ALLEIN GOTT IN DER HOH'),
(900,'Jesus! Name of Wondrous Love','GOTT SEI DANK'),
(901,'Open Now Thy Gates of Beauty','UNSER HERRSCHER'),
(902,'Lord Jesus Christ, Be Present Now','HERR JESU CHRIST, DICH ZU UNS WEND'),
(903,'This Is the Day the Lord Has Made','NUN DANKET ALL'),
(904,'Blessed Jesus, at Your Word','LIEBSTER JESU, WIR SIND HIER'),
(905,'Come, Thou Almighty King','ITALIAN HYMN'),
(906,'O Day of Rest and Gladness','ELLACOMBE'),
(907,'God Himself is Present','WUNDERBARER KONIG'),
(908,'Lord, Open Now My Heart to Hear','ERHALT UNS, HERR'),
(909,'Christ Is Made the Sure Foundation','WESTMINSTER ABBEY'),
(910,'Now the Silence','NOW'),
(911,'Lord, This Day We''ve Come to Worship','GLORIOUS NAME'),
(912,'Christ Is Our Cornerstone','DARWALL''S 148TH'),
(913,'O Holy Spirit, Enter In','WIE SCHON LEUCHTET'),
(914,'Light of Light, O Sole-Begotten','WESTMINSTER ABBEY'),
(915,'Today Your Mercy Calls Us','ANTHES'),
(916,'Only-Begotten Word of God Eternal','ISTE CONFESSOR'),
(917,'Savior, Again to Thy Dear Name We Raise','ELLERS'),
(918,'Guide me, O Thou Great Redeemer','CWM RHONDDA'),
(919,'Abide, O Dearest Jesus','CHRISTUS, DER IST MEIN LEBEN'),
(920,'Forth in the Peace of Christ We Go','ANGELUS'),
(921,'On What Has Now Been Sown','DARWALL''S 148TH'),
(922,'Go, My Children, with My Blessing','AR HYD Y NOS'),
(923,'Almighty Father, Bless the Word','OLD HUNDREDTH'),
(924,'Lord, Dismiss Us with Your Blessing','REGENT SQUARE'),
(925,'Song of Moses and Israel','[I will sing to the LORD]'),
(926,'Song from Deuteronomy','[The LORD will vindicate His people]'),
(927,'First Song of Isaiah','[The LORD GOD is my strength and my song]'),
(928,'Song of Hannah','[My heart exults in the LORD]'),
(929,'I Will Greatly Rejoice in the Lord','[The Lord GOD will cause righteousness and praise]'),
(930,'All You Works of God, Bless the Lord','LINSTEAD'),
(931,'All You Works of the Lord','[Praise Him and magnify Him forever]'),
(932,'Jesus Sat with His Disciples','JOYOUS LIGHT'),
(933,'My Soul Rejoices','IN DIR IST FREUDE'),
(934,'My Soul Now Magnifies the Lord','WO GOTT ZUM HAUS'),
(935,'Tell Out, My Soul, the Greatness of the Lord','WOODLANDS'),
(936,'Sing Praise to the God of Israel','DEN SIGNEDE DAG'),
(937,'Lord, Bid Your Servant Go in Peace','LAND OF REST'),
(938,'In Peace and Joy I Now Depart','MIT FRIED UND FREUD'),
(939,'You Are God; We Praise You','[You are God: we praise You]'),
(940,'Holy God, We Praise Thy Name','GROSSER GOTT'),
(941,'We Praise You and Acknowledge You, O God','THAXTED'),
(942,'Kyrie! God, Father','KYRIE, GOTT VATER'),
(943,'Kyrie - I (Lord, Have Mercy)','[Kyrie, Kyrie eleison]'),
(944,'Kyrie - II (Lord, Have Mercy)','[Kyrie eleison]'),
(945,'Your Heart, O God, Is Grieved','ZNAME TO, PANE BOZE NAS'),
(946,'Glory to God, We Give You Thanks and Praise','WOODLANDS'),
(947,'All Glory Be to God on High','ALLEIN GOTT IN DER HOH'),
(948,'All glory be to God alone','ALL EHR UND LOB'),
(949,'Heavenly Hosts in Ceaseless Worship','LOVE''S LIGHT'),
(950,'Splendor and Honor','SHADES MOUNTAIN'),
(951,'Alleluia - I','[Alleluia, alleluia, alleluia]'),
(952,'Alleluia - II','[Alleluia, alleluia]'),
(953,'We All Believe in One True God','WIR GLAUBEN ALL (Metrical)'),
(954,'We All Believe in One True God','WIR GLAUBEN ALL (Chant)'),
(955,'Let the Vineyards Be Fruitful','[Let the vineyards be fruitful, Lord]'),
(956,'Create in Me','SCHAFFE IN MIR, GOTT'),
(957,'Our Father Who Art in Heaven - I','[Our Father who art in heaven]'),
(958,'Our Father Who Art in Heaven - IIa','PADRE NUESTRO'),
(959,'Our Father Who Art in Heaven - IIb','PADRE NUESTRO'),
(960,'Isaiah, Mighty Seer in Days of Old','JESAIA, DEM PROPHETEN'),
(961,'Sanctus (Holy, Holy, Holy)','[Holy, holy, holy Lord God of Sabaoth]'),
(962,'Agnus Dei - I (Lamb of God)','[Lamb of God]'),
(963,'Agnus Dei - II (Lamb of God)','[Lamb of God]'),
(964,'Lift Every Voice and Sing','LIFT EVERY VOICE'),
(965,'God Bless Our Native Land','NATIONAL ANTHEM'),
(966,'Before You, Lord, We Bow','DARWALL''S 148TH');

UPDATE tblHymn h
JOIN tblHymnal y ON y.ID=h.HymnalID
JOIN tmp_lsb_printed_tune t
  ON CAST(SUBSTRING_INDEX(TRIM(h.Hymn),' ',-1) AS UNSIGNED)=t.HymnNumber
SET h.Tune=t.Tune
WHERE UPPER(TRIM(y.Hymnal))='LSB'
  AND t.HymnNumber BETWEEN 331 AND 966;

DROP TEMPORARY TABLE tmp_lsb_printed_tune;

CREATE OR REPLACE SQL SECURITY DEFINER VIEW rpt_hymn AS
SELECT ID,HymnalID,Hymn,Title,Tune,BibleText,Category,File,Image,Note
FROM tblHymn;
