-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Apr 15, 2023 at 03:17 PM
-- Server version: 10.6.7-MariaDB
-- PHP Version: 7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `churchdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `tblservice`
--

DROP TABLE IF EXISTS `tblservice`;
CREATE TABLE IF NOT EXISTS `tblservice` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `ChurchID` int(11) DEFAULT NULL,
  `DateTime` datetime NOT NULL,
  `PropersID` int(11) DEFAULT NULL,
  `LiturgicalDate` varchar(255) DEFAULT NULL,
  `HolyCommunion` tinyint(1) DEFAULT NULL,
  `OrderofService` varchar(255) DEFAULT NULL,
  `OSNote` varchar(255) DEFAULT NULL,
  `PsalmorIntroit` varchar(255) DEFAULT NULL,
  `SermonID` int(11) DEFAULT NULL,
  `Bulletin` varchar(255) DEFAULT NULL,
  `Attendance` int(11) DEFAULT NULL,
  `CommunionAttendance` int(11) DEFAULT NULL,
  `CountforAttendance` int(11) DEFAULT NULL,
  `CheckListComplete` tinyint(1) DEFAULT NULL,
  `CheckListID` int(11) DEFAULT NULL,
  `CheckList` longtext DEFAULT '{}',
  `Note` longtext DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=57 DEFAULT CHARSET=utf8mb3;

--
-- Dumping data for table `tblservice`
--

INSERT INTO `tblservice` (`ID`, `ChurchID`, `DateTime`, `PropersID`, `LiturgicalDate`, `HolyCommunion`, `OrderofService`, `OSNote`, `PsalmorIntroit`, `SermonID`, `Bulletin`, `Attendance`, `CommunionAttendance`, `CountforAttendance`, `CheckListComplete`, `CheckListID`, `CheckList`, `Note`) VALUES
(1, 0, '2022-12-07 09:00:00', 2, 'Second Sunday in Advent', 1, 'DS1 (151)', NULL, '\r\nIntroit', 9, NULL, NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"False\", \"Worship Planning, Complete\": \"False\", \"Worship Planning, Printed\": \"False\", \"Participents Scheduled\": \"False\", \"Particpients Notified\": \"False\", \"Bulletin, Prepared\": \"False\", \"Bulletin, Printed\": \"False\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"False\", \"Sermon, Printed\": \"False\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"False\"}', NULL),
(2, 0, '2022-08-21 09:00:00', 234, 'The Eleventh Sunday after Pentecost', 1, 'DS4 (203)', NULL, '\r\nIntroit', 10, 'LiC.Bulletin.21-Aug-22.pub', NULL, NULL, NULL, 1, 0, NULL, NULL),
(4, 0, '2022-08-28 09:00:00', 235, 'Twelfth Sunday after Pentecost', 1, 'DS4 (203)', NULL, 'Introit', 12, 'LiC.Bulletin.28-Aug-22.pub', NULL, NULL, NULL, 1, 2, NULL, '[Note]'),
(5, 0, '2022-09-04 09:00:00', 236, 'Thirteenth Sunday after Pentecost', 1, 'DS4', NULL, 'Introit', 13, 'LiC.Bulletin.4-Sep-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"False\", \"Participents Scheduled\": \"False\", \"Particpients Notified\": \"False\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(6, 0, '2022-09-11 09:00:00', 237, 'The Fourtheeth Sunday after Pentecost', 1, 'DS1', NULL, 'Introit', 15, 'LiC.Bulletin.11-Sep-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"False\", \"Participents Scheduled\": \"True\", \"Particpients Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"True\"}', NULL),
(7, 0, '2022-09-18 09:00:00', 238, 'Fifteenth Sunday after Pentecost', 1, 'DS1', NULL, 'Introit', 16, 'LiC.Bulletin.18-Sep-22.pub', NULL, NULL, NULL, 1, 2, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participents Scheduled\": \"True\", \"Particpients Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\", \"Concordia Organist, Prepared\": \"True\"}', NULL),
(8, 0, '2022-09-25 09:00:00', 239, 'Sixteenth Sunday after Pentecost', 1, 'DS1', NULL, 'Introit', 17, 'LiC.Bulletin.25-Sep-22.pub', NULL, NULL, NULL, 0, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participents Scheduled\": \"True\", \"Particpients Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(9, 0, '2022-10-02 09:00:00', 240, 'Seventeenth Sunday after Pentecost', 1, 'DS1', NULL, 'Introit', 18, 'LiC.Bulletin.2-Oct-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participents Scheduled\": \"True\", \"Particpients Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"False\"}', NULL),
(10, 0, '2022-10-09 09:00:00', 241, 'Eighteenth Sunday after Pentecost', 1, 'DS1', NULL, 'Introit', 19, 'LiC.Bulletin.9-Oct-22.pub', NULL, NULL, NULL, 1, 2, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participents Scheduled\": \"True\", \"Particpients Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\", \"Concordia Organist, Prepared\": \"True\"}', NULL),
(11, 0, '2022-10-16 09:00:00', 242, 'The Nineteenth Sunday after Pentecost', 1, 'DS1', NULL, 'Introit', 20, 'LiC.Bulletin.19-Oct-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participents Scheduled\": \"True\", \"Particpients Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(12, 0, '2022-10-23 09:00:00', 243, 'Twentieth Sunday after Pentecost', 1, 'DS1', NULL, 'Introit', NULL, 'LiC.Bulletin.23-Oct-22.pub', NULL, NULL, NULL, 0, 2, NULL, NULL),
(13, 0, '2022-10-30 09:00:00', 342, 'Festival of the Reformation', 1, 'DS1', NULL, 'Introit', NULL, 'LiC.Bulletin.30-Oct-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"False\", \"Sermon, Printed\": \"False\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"True\"}', NULL),
(14, 0, '2022-10-27 18:06:00', 343, 'The Festival of All Saints', 1, 'DS1', NULL, 'Introit', NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL),
(15, 0, '2022-11-06 09:00:00', 343, 'The Festival of All Saints', 1, 'DS1', NULL, 'Psalm', 22, 'LiC.Bulletin.6-Nov-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', '[Note! Psalm instead of Introit.]'),
(16, 0, '2022-11-13 09:00:00', 246, 'Twenty-Third Sunday after Pentecost', 1, 'DS1', NULL, 'Introit', 23, 'LiC.Bulletin.13-Nov-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"False\"}', NULL),
(17, 0, '2022-11-27 09:00:00', 1, 'First Sunday in Advent', 1, 'DS3', '[Gloira omitted during Advent]', 'Introit', NULL, 'LiC.Bulletin.27-Nov-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Prayers, Printed\": \"True\"}', '[NB!! the change to DS3]'),
(18, 0, '2022-11-20 09:00:00', 247, 'Last Sunday of the Church Year', 1, 'DS1', NULL, 'Introit', 24, 'Lic.Bulletin.20-Nov-22.pub', NULL, NULL, NULL, 1, 2, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participents Scheduled\": \"True\", \"Particpients Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Bulletin, Posted to Website\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\", \"Concordia Organist, Prepared\": \"False\"}', NULL),
(19, 0, '2022-11-23 18:30:00', 347, 'Thanksgiving Eve', 0, 'Vespers', NULL, 'Psalm', 25, 'LiC.Bulletin.23-Nov-22.docx', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"True\"}', NULL),
(20, 0, '2022-11-30 18:30:00', 354, 'Weekday Advent Servcie One', 0, 'Vespers', NULL, 'None', 26, 'LiC.Bulletin.30-Nov-22.docx', NULL, NULL, NULL, 1, 7, '{\"Devotions, Printed\": \"False\", \"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"False\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\"}', '[Replace Magnificat with LSB933\rPrint Family Devoctions ]'),
(21, 0, '2022-12-04 09:00:00', 2, 'Second Sunday in Advent', 1, 'DS3', '[Use Gloria p. 186 instead of Gloria Patra  in Introit.]', 'Introit', 27, 'LiC.Bulletin.4-Dec-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(22, 0, '2022-12-07 06:30:00', 354, 'Weekday Advent 2', 0, 'Vespers', '[Prayer of the Church - \rEvening Prayer Litany - p.249]', 'None', 28, 'LiC.Bulletin.7-Dec-22.docx', NULL, NULL, NULL, 1, 3, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Particpiants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\"}', NULL),
(23, 0, '2022-12-11 09:00:00', 3, 'Third Sunday in Advent', 1, 'DS3', '[Use Gloria p. 186 instead of Gloria Patra  in Introit.]', 'Introit', 29, 'LiC.Bulletin.11-Dec-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(24, 0, '2022-12-21 18:30:00', 354, 'Weekday Advent 4', 0, 'Vespers', '[We will use the Magnifcat from Vespers p.231]', 'None', 30, 'LiC.Bulletin.14-Dec-22.docx', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"True\"}', NULL),
(25, 0, '2022-12-18 09:00:00', 4, 'Fourth Sunday in Advent', 0, 'DS3', NULL, 'Introit', 31, 'LiC.Bulletin.18-Dec-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', '[Lisa if you are planning to sing Oh Come... I will pick a different hymn for the Hymn of the Day]'),
(26, 0, '2022-12-24 18:30:00', 5, 'Nativity of Our Lord', 0, 'Evening Prayer', NULL, 'None', 35, 'LiC.Bulletin.24-Dec-22.docx', NULL, NULL, NULL, 1, 3, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Particpiants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Prayers, Printed\": \"False\"}', '[Special Hymn \"Night of Silence\" Onelicense.net #A-741154]'),
(29, 0, '2022-12-25 09:00:00', 8, 'The Nativity of Our Lord', 1, 'DS3', NULL, 'Introit', 36, 'LiC.Bulletin.25-Dec-22.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', '[Hymn of the Day: God Rest Ye Merry Gentlemen. Insert\rOneLicense #A-741154]'),
(30, 0, '2023-01-01 09:00:00', 9, 'The First Sunday after Christmas', 1, 'DS3', NULL, 'Introit', 37, 'LiC.Bulletin.1-Jan-23.pub', NULL, NULL, NULL, 1, 0, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"False\"}', '[NB! Change to DS3]'),
(31, 0, '2023-01-08 09:00:00', 11, 'The Epiphany of Our Lord', 1, 'DS4', NULL, 'Introit', 38, 'LiC.Bulletin.8-Jan-23.pub', NULL, NULL, NULL, 1, 2, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(32, 0, '2023-01-15 09:00:00', 12, 'Baptism of Our Lord', 1, 'DS4', NULL, 'Introit', 39, 'LiC.Bulletin.15-Jan-23.pub', NULL, NULL, NULL, 0, 0, NULL, NULL),
(33, 0, '2023-01-22 09:00:00', 14, 'Third Sunday after the Epiphany', 1, 'DS4', NULL, 'Psalm', 40, 'LiC.Bulletin.22-Jan-23.pub', NULL, NULL, NULL, 0, NULL, NULL, NULL),
(34, NULL, '2023-01-19 09:00:00', NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, '{}', NULL),
(35, 0, '2023-01-29 09:00:00', 355, 'The Fourth Sunday after the Epiphany', 1, 'DS4', NULL, 'Introit', 42, 'LiC.Bulletin.29-Jan-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"False\", \"Participants Scheduled\": \"False\", \"Participants Notified\": \"False\", \"Bulletin, Prepared\": \"False\", \"Bulletin, Printed\": \"False\", \"Sermon, Prepared\": \"False\", \"Sermon, Printed\": \"False\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"False\"}', NULL),
(37, 0, '2023-02-05 09:00:00', 15, 'The Fifth Sunday after the Epiphany', 1, 'DS4', NULL, 'Introit', 43, 'LiC.Bulletin.5-Mar-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(38, 0, '2023-02-12 09:00:00', 16, 'The Sixth Sunday after the Epiphany', 1, 'DS4', NULL, 'Psalm', 44, 'LiC.Bulletin.12-Feb-23.pub', NULL, NULL, NULL, 0, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"False\", \"Concordia Organist, Prepared\": \"False\"}', '[Lisa and Jay are scheduled to be gone.]'),
(39, 0, '2023-02-19 09:00:00', 19, 'The Transfiguration of Our Lord', 1, 'DS3', NULL, 'Introit', 45, 'LiC.Bulletin.17-Feb-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(40, 0, '2023-02-22 18:30:00', 20, 'Ash Wednesday', 0, 'DS1', '[Modified DS1 w/o Communion\rw/ Imposition of Ashes]', 'Psalm', 46, 'LiC.Bulletin.22-Feb-23.docx', NULL, NULL, NULL, 1, NULL, '{\"Ashes Prepared\": \"True\", \"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Particpiants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\"}', NULL),
(41, 0, '2023-02-26 09:00:00', 21, 'The First Sunday in Lent', 1, 'DS1', NULL, 'Introit', 48, 'LiC.Bulletin.26-Feb-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\"}', NULL),
(42, 0, '2023-03-01 18:30:00', 356, 'Weekday Lent 1', 0, 'Compline', '[Prayer of the Day: Psalm 51\rChanted]', NULL, 49, 'LiC.Bulletin.1-Mar-23.docx', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\"}', NULL),
(47, 0, '2023-03-19 09:00:00', 24, 'The Fourth Sunday in Lent', 1, 'DS1', NULL, 'Psalm', 56, 'LiC.Bulletin.19-Mar-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"False\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"False\"}', NULL),
(43, 0, '2023-03-05 09:00:00', 22, 'Second Sunday in Lent', 1, 'DS1', '[Prayer of the Day\rLitany LSB p.288]', 'Introit', 50, 'LiC.Bulletin.5-Mar-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\"}', NULL),
(44, 0, '2023-03-08 18:30:00', 356, 'Weekday Lent Two', 0, 'Compline', '[Nunc Dimittus DS3 p.199]', 'None', 52, 'LiC.Bulletin.8-Mar-23.docx', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"False\", \"Concordia Organist, Prepared\": \"False\"}', NULL),
(45, 0, '2023-03-12 09:00:00', 23, 'The Third Sunday in Lent', 1, 'DS1', '[Prayer of the Day Litany p.288]', 'Introit', 53, 'LiC.Bulletin.12-Mar-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\"}', NULL),
(46, 0, '2023-03-15 18:30:00', 356, 'Weekday Lenten Service 3', 0, 'Compline', NULL, 'None', 54, 'LiC.Bulletin.15-Mar-23.docx', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Particpiants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Readings, Printed\": \"True\"}', NULL),
(48, 0, '2023-03-22 18:30:00', 356, 'Weekday Lent Service 4', 0, 'Compline', '[Office Hymn: How Deep the Fathers Love for Us CCLI# 5473617]', 'None', 57, 'LiC.Bulletin.22-Mar-23.docx', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Particpiants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"False\"}', NULL),
(49, 0, '2023-03-26 09:00:00', 25, 'The Fifth Sunday in Lent', 1, 'DS1', NULL, 'Introit', 58, 'LiC.Bulletin.26-Mar-2023.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\"}', NULL),
(50, 0, '2023-03-29 18:30:00', 356, 'Weekday Lent 5', 0, 'Compline', NULL, 'None', 59, 'LiC.Bulletin.29-Mar-23.docx', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Particpiants Notified\": \"True\", \"Readings, Selected\": \"True\", \"Readings, Printed\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\"}', NULL),
(51, 0, '2023-04-02 09:00:00', 26, 'Palm / Passion Sunday', 1, 'DS1', '[Service begins with Procession of Palms then continues with reading of the Passion of Our Lord Jesus Christ]', 'None', 60, 'LiC.Bulletin.2-Apr-22.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\"}', NULL),
(55, 0, '2023-04-09 09:00:00', 33, 'The Resurrection of Our Lord, Jesus Christ', 1, 'DS1', '[Easter Processional with Dedication of the Christ Candle.]', 'Psalm', 63, 'LiC.Bulletin.9-Apr-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"True\", \"Prayers, Printed\": \"True\"}', NULL),
(53, 0, '2023-04-06 18:30:00', 30, 'Holy Thursday', 1, 'Other', '[Corporate Confession p. 290\rService concludes with Stripping of the Altar and Reading Psalm 22.]', 'None', 62, 'LiC.Bulletin.6-Apr-23.pub', NULL, NULL, NULL, 1, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"True\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"True\"}', NULL),
(54, 0, '2023-04-07 18:30:00', 31, 'Good Friday', 0, 'Other', '[The Congregation assembles and departs in silence.]', NULL, 61, 'Good Friday (Tenebrae Vespers).docx', NULL, NULL, NULL, 0, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"False\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"True\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"True\", \"Sermon, Posted to Blog\": \"False\"}', NULL),
(56, 0, '2023-04-16 09:00:00', 38, 'Second Sunday of Easter', 1, 'DS1', NULL, 'Introit', 64, 'LiC.Bulletin.16-Apr-23.pub', NULL, NULL, NULL, 0, NULL, '{\"Hymns, Selected\": \"True\", \"Worship Planning, Complete\": \"True\", \"Worship Planning, Printed\": \"False\", \"Participants Scheduled\": \"True\", \"Participants Notified\": \"True\", \"Bulletin, Prepared\": \"True\", \"Bulletin, Printed\": \"False\", \"Sermon, Prepared\": \"True\", \"Sermon, Printed\": \"False\", \"Sermon, Posted to Blog\": \"False\", \"Prayers, Printed\": \"False\", \"Concordia Organist, Prepared\": \"False\"}', NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
